apiVersion: v1
kind: ConfigMap
metadata:
  name: maple-prometheus-configmap
  namespace: maple-monitor
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'maple-service-envoy-metrics-job'
        metrics_path: '/stats/prometheus'
        static_configs:
          - targets: ['maple-api-router-service.maple-system.svc.cluster.local:9901']
          - targets: ['maple-user-auth-service.maple-system.svc.cluster.local:9901']
          - targets: ['maple-user-account-service.maple-system.svc.cluster.local:9901']
          - targets: ['maple-organization-service.maple-system.svc.cluster.local:9901']
          - targets: ['maple-project-service.maple-system.svc.cluster.local:9901']
          - targets: ['maple-architecture-service.maple-system.svc.cluster.local:9901']
      - job_name: 'maple-service-actuator-metrics-job'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['maple-api-router-service.maple-system.svc.cluster.local:8081']
          - targets: ['maple-user-auth-service.maple-system.svc.cluster.local:8081']
          - targets: ['maple-user-account-service.maple-system.svc.cluster.local:8081']
          - targets: ['maple-organization-service.maple-system.svc.cluster.local:8081']
          - targets: ['maple-project-service.maple-system.svc.cluster.local:8081']
          - targets: ['maple-architecture-service.maple-system.svc.cluster.local:8081']


