apiVersion: v1
kind: ConfigMap
metadata:
  name: maple-prometheus-configmap
  namespace: maple-monitor
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'maple-envoy'
        metrics_path: '/stats/prometheus'
        static_configs:
          - targets: ['maple-api-router-service.maple-system.svc.cluster.local:9901']
