apiVersion: v1
kind: Service
metadata:
  name: maple-zipkin-service
  namespace: maple-tracing
  labels:
    app: maple-zipkin
spec:
  type: ClusterIP
  ports:
    - port: 9411
      targetPort: 9411
  selector:
    app: maple-zipkin
