version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/maple-service-redeployer:$CIRCLE_SHA1 -t $DOCKERHUB_USERNAME/maple-service-redeployer:latest scripts/deployer/
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker image
          command: |
            docker push $DOCKERHUB_USERNAME/maple-service-redeployer:$CIRCLE_SHA1
            docker push $DOCKERHUB_USERNAME/maple-service-redeployer:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push:
          context:
            - shared-credentials
          filters:
            branches:
              only: master
