apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: maple-system
  name: deployment-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update", "patch", "list", "create", "delete"]
